### ISSUE TITLE
Unfilled patches between contours

### ISSUE THREAD

**Issue by Plantain** [bartromgens/geojsoncontour#11]
Sometimes there's little unfilled gaps between the contours. Using ndigits=99, so seems unlikely to be an issue with precision.
<img width="582" alt="screen shot 2018-06-19 at 8 58 44 pm" src="https://user-images.githubusercontent.com/319895/41618517-a934977e-7403-11e8-95f2-2799eb6e50e4.png">
<img width="237" alt="screen shot 2018-06-19 at 8 56 56 pm" src="https://user-images.githubusercontent.com/319895/41618518-a9558dee-7403-11e8-82ea-0820880938e9.png">

**Comment by Plantain** [comment]
[1000.json.zip](https://github.com/bartromgens/geojsoncontour/files/2116617/1000.json.zip)
Example JSON attached

**Comment by MarySymons** [comment]
Did you try using min_angle_degree = 0? That removed any gaps in my contours :)

**Comment by bartromgens** [comment]
This should indeed not happen when `min_angle_deg` is `0` or `None`. The default was changed to `None` about a year ago, so the default behavior should not have gaps anymore. I consider this closed. Feel free to reopen if it is not related to `min_angle_deg`.
