### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by wormone** [bartromgens/geojsoncontour#2]
Thanks for this solution :+1: 
I had tried converting contouf plot to geojson polygens, but there seemed some bug in displaying the output geojson by leaflet.js, becasue the polygens are finaly rendered with SVG in the browser. The path defined in SVG has it's own rules and some complicate polygens derived from matplotlib can not be simply converted to geojson polygens correctly. I have not yet figured it out.

```
import numpy as np
import simplejson as json
from geojson import Polygon, Feature, FeatureCollection
def contourf_to_geojson(cs):
    """ cs = plt.contourf(...) """
    allsegs = cs.allsegs
    levels = cs.levels
    tcolors = cs.tcolors
    features = []
    for level in range(len(allsegs)):
        seg = allsegs[level]
        if seg:
            for _ in range(len(seg)):
                poly = np.round(seg[_], 3).tolist()
                poly = poly[::-1] # necessary
                poly = Polygon([poly])
                feature = Feature(geometry=poly, properties={"level": level, "color": tcolors[level][0]})
                features.append(feature)
    features = FeatureCollection(features)
    features = json.dumps(features)
    with open('features.json', 'w') as fc:
        fc.write(features)
```

**Comment by bartromgens** [comment]
@wormone did you manage to figure this out? I would like to create a new release if we have contourf polygons working.
