### ISSUE TITLE
Geojsoncontour issue in shell script

### ISSUE THREAD

**Issue by iwuzhu** [bartromgens/geojsoncontour#23]
I can ran my Python script correctly with python command such as 
$python rainfall_contour.py

Unfortunately, the same command in a shell script caused error "ModuleNotFoundError: No module named 'geojsoncontour'". geojsoncontour has been correctly installed. How to eliminate this error?

**Comment by bartromgens** [comment]
This sounds like a general Python question. You need to install geojsoncontour in the (virtual)environment that you use when running a script. It is likely not installed in the environment, and for the Python version, when you run the shell script.
