### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by lewisblake** [bartromgens/geojsoncontour#25]
We use this project in [pyaerocom](https://github.com/metno/pyaerocom) which is developed at the Norwegian Meteorological Institute for air quality and climate model evaluation and therefore have a vested interest in this project's survival. We could contribute to the maintenance, or even take over it's development if necessary as part of our day jobs. Please let us know how we can contribute to the survival of this project. It's very useful! :)

**Comment by bartromgens** [comment]
@lewisblake this project isn't completely abandoned and I'm still here to accept pull requests and release new versions. However, I don't actively develop it and welcome someone to more actively maintain it. It is not a lot of code so there is also not a lot to maintain, except for some update/modernization of dependencies and packaging maybe. 

I'm can give you (or others) access to maintain this project and release new versions to pypi. What do you prefer?

**Comment by bartromgens** [comment]
I understand you are looking to fix https://github.com/bartromgens/geojsoncontour/issues/24 

I have not looked into the issue, but had hoped this was something matplotlib would fix. If they don't consider this a bug, then it should be fixed here. https://pypi.org/project/geojson-rewind/ could probably fix it, but adds another dependency.

**Comment by lewisblake** [comment]
Thanks for the quick response. For us right now, the packaging is the most important thing. If you could give myself and @jgriesfeller maintainer access that would be very helpful. We can then look into #24 in more detail.

**Comment by bartromgens** [comment]
@lewisblake I have invited you both to the pypi and github project.

**Comment by bartromgens** [comment]
Thank you for your help @lewisblake @jgriesfeller! Feel free to do what you think is best for this project! I'll keep an eye on it and am willing to help, but don't need to be involved.
