### ISSUE TITLE
No utilities by using pip install

### ISSUE THREAD

**Issue by HuangLiPang** [bartromgens/geojsoncontour#6]
When I try to install geojsoncontour by using pip, it did not install the utilities package.
I need to add the utility from this repository by myself.

**Comment by ghost** [comment]
This has been fixed in master but the new package isn't released yet. In the meantime, you can [install from the git repo using pip](https://pip.pypa.io/en/stable/reference/pip_install/#git).

**Comment by bartromgens** [comment]
I will try to release a new version today.

**Comment by HuangLiPang** [comment]
Thank you! @amarandon @bartromgens

**Comment by bartromgens** [comment]
Just released 0.2.1. Let me know if there are any issues and thanks for giving me a heads up on this issue.
