### ISSUE TITLE
Add option to return a Python data structure instead of a string

### ISSUE THREAD

**Issue by ghost** [bartromgens/geojsoncontour#7]
I would like to add an option to return a Python data structure instead of a string. My use case is adding a GeoJSON layer to ipyleaflet which takes a Python structure. Of course it's very easy to call json.loads on the output of geojsoncontour, but it adds unnecessary serialization/deserialization. Maybe we could add a `serialize` keyword argument which would be `True` by default?

**Comment by bartromgens** [comment]
That makes sense and makes it more general.
