### ISSUE TITLE
Package "not compatible with this Python"

### ISSUE THREAD

**Issue by ghost** [bartromgens/geojsoncontour#9]
Hi,

I'm trying to install the 0.2.1 release of this package from PyPI but apparently there's an issue with the wheel filename.
```
$ pip install -v geojsoncontour==0.2.1
Collecting geojsoncontour==0.2.1
  1 location(s) to search for versions of geojsoncontour:
  * https://pypi.python.org/simple/geojsoncontour/
[...]
    Skipping link https://pypi.python.org/packages/fd/08/24a58eb329126dad04b7010a1132dd4fa653aaec348cd3c28484289a0949/geojsoncontour-0.2.1-py3-release-any.whl#md5=aba2a5f556b1528e0cb9594a23a76a7a (from https://pypi.python.org/simple/geojsoncontour/); it is not compatible with this Python
[...]
```

I think the reason why it refuses to install it is because the filename contains `release`  where [it should contain `none`](https://www.python.org/dev/peps/pep-0427/#file-name-convention). If you look at the previous wheel files, their filename was containing `none` as abi tag filename part.

**Comment by bartromgens** [comment]
@amarandon Thanks for the heads-up and sorry for the inconvenience. I am apparently not very good at building wheels :/ and should have tested it. 

I have just released a new version that should work; I have tested a fresh install.

**Comment by ghost** [comment]
@bartromgens No worries, and thank your for this wonderful package. It makes it so easy to add a contour layer to a leaflet map.
